/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'studentId' : string,
  'present' : boolean,
  'date' : bigint,
  'notes' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Gallery {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface Image {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'galleryId' : string,
}
export interface Review {
  'review' : string,
  'subjects' : [] | [string],
  'fullName' : string,
  'approved' : boolean,
  'timestamp' : bigint,
  'rating' : [] | [number],
  'classYear' : string,
}
export interface Student {
  'id' : string,
  'name' : string,
  'enrollmentDate' : bigint,
  'className' : string,
}
export interface TestResult {
  'studentId' : string,
  'maxScore' : bigint,
  'subject' : string,
  'testDate' : bigint,
  'score' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addImage' : ActorMethod<
    [string, ExternalBlob, string, string, string],
    boolean
  >,
  'addTestResult' : ActorMethod<
    [string, string, bigint, bigint, bigint],
    undefined
  >,
  'approveReview' : ActorMethod<[string], boolean>,
  'createGallery' : ActorMethod<[string, string, string], boolean>,
  'createStudent' : ActorMethod<[string, string, string, bigint], undefined>,
  'deleteGallery' : ActorMethod<[string], boolean>,
  'deleteImage' : ActorMethod<[string], boolean>,
  'getAllGalleries' : ActorMethod<[], Array<Gallery>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getApprovedReviews' : ActorMethod<[], Array<Review>>,
  'getGallery' : ActorMethod<[string], [] | [Gallery]>,
  'getImage' : ActorMethod<[string], [] | [Image]>,
  'getImagesByGallery' : ActorMethod<[string], Array<Image>>,
  'getStudent' : ActorMethod<[string], [] | [Student]>,
  'getStudentAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getStudentTestResults' : ActorMethod<[string], Array<TestResult>>,
  'recordAttendance' : ActorMethod<
    [string, bigint, boolean, [] | [string]],
    undefined
  >,
  'submitReview' : ActorMethod<
    [string, string, [] | [string], string, [] | [number]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];